### ISSUE TITLE
Static resources can not be found (404 for all content in vendor folder)

### ISSUE THREAD

**Issue by ChocoMachine** [sfmskywalker/Skywalker.Website#1]
Hi just downloaded this to have a look, to see what I could learn.

Anyways all the static resources in the vendor folder are not resolved, 404s

Clone in to new folder
build
run
browse.

**Comment by ChocoMachine** [comment]
I think you need to add

`   app.UseStaticFiles();`

in your startup.cs

**Comment by sfmskywalker** [comment]
That’s odd, I didn’t have that problem myself. You do need to do `npm rum build` from the theme folder first though.
